### ISSUE TITLE
upgrade for react 16

### ISSUE THREAD

**Issue by tyler-johnson** [vleletko/react-frame-aware-selection-plugin#6]
It seems like react-dom 16 changed some internal paths, so now I get errors like "Can't resolve 'react-dom/lib/BeforeInputEventPlugin'". Is it possible to upgrade this plugin for react 16? Thanks.

**Comment by vleletko** [comment]
Updated to react 16, tests work fine, however, I didn't test the Slate.

**Comment by sethmcleod** [comment]
@vleletko I'm seeing an error related to the HTMLNodeType constant.

![image](https://user-images.githubusercontent.com/7340187/31440889-6ed7bbac-ae5f-11e7-814c-69be6374cedd.png)

Should this line https://github.com/vleletko/react-frame-aware-selection-plugin/blob/develop/src/getNodeForCharacterOffset.js#L12 be `require('./HTMLNodeType')` instead of `require('HTMLNodeType')`?

**Comment by cmmartin** [comment]
Not sure how the tests pass. `react-dom/lib` has been moved so all of these now fail in version 16...

```
Can't resolve 'react-dom/lib/isTextInputElement'
Can't resolve 'react-dom/lib/SyntheticEvent'
Can't resolve 'react-dom/lib/SimpleEventPlugin'
Can't resolve 'react-dom/lib/ReactInputSelection'
Can't resolve 'react-dom/lib/ReactDOMComponentTree'
Can't resolve 'react-dom/lib/EventPropagators'
```

**Comment by cmmartin** [comment]
@sethmcleod  @vleletko Sent a PR for this [#7](https://github.com/vleletko/react-frame-aware-selection-plugin/pull/7)
